QUESTION_BANK = {

    "graphic design": [
        {"id": "gd1", "difficulty": "easy", "type": "mcq",
         "question": "What does RGB stand for?",
         "options": ["Red Green Blue", "Right Grey Balance", "Rapid Graphic Build", "Red Grey Black"],
         "answer": "Red Green Blue"},
        {"id": "gd2", "difficulty": "easy", "type": "mcq",
         "question": "Which file format supports transparency?",
         "options": ["JPEG", "PNG", "BMP", "DOCX"],
         "answer": "PNG"},
        {"id": "gd3", "difficulty": "easy", "type": "mcq",
         "question": "What is the standard resolution for print design?",
         "options": ["72 DPI", "150 DPI", "300 DPI", "1080 DPI"],
         "answer": "300 DPI"},
        {"id": "gd4", "difficulty": "easy", "type": "mcq",
         "question": "Which tool is primarily used for vector graphics?",
         "options": ["Photoshop", "Illustrator", "Premiere Pro", "Excel"],
         "answer": "Illustrator"},
        {"id": "gd5", "difficulty": "easy", "type": "text",
         "question": "What is negative space in design?"},

        {"id": "gd6", "difficulty": "medium", "type": "mcq",
         "question": "Which color model is used for print?",
         "options": ["RGB", "CMYK", "HSB", "Pantone"],
         "answer": "CMYK"},
        {"id": "gd7", "difficulty": "medium", "type": "mcq",
         "question": "What is kerning?",
         "options": ["Space between paragraphs", "Space between individual letters", "Font weight", "Line height"],
         "answer": "Space between individual letters"},
        {"id": "gd8", "difficulty": "medium", "type": "text",
         "question": "Explain the rule of thirds in composition."},
        {"id": "gd9", "difficulty": "medium", "type": "mcq",
         "question": "Which file format is best for scalable logos?",
         "options": ["JPEG", "SVG", "BMP", "GIF"],
         "answer": "SVG"},
        {"id": "gd10", "difficulty": "medium", "type": "text",
         "question": "What is the difference between serif and sans-serif fonts?"},

        {"id": "gd11", "difficulty": "hard", "type": "text",
         "question": "Explain visual hierarchy and how you'd apply it to a landing page design."},
        {"id": "gd12", "difficulty": "hard", "type": "mcq",
         "question": "What is the golden ratio commonly used for in design?",
         "options": ["Color mixing", "Aesthetically pleasing proportions", "File compression", "Font pairing"],
         "answer": "Aesthetically pleasing proportions"},
        {"id": "gd13", "difficulty": "hard", "type": "text",
         "question": "How would you ensure brand consistency across multiple design deliverables?"},
        {"id": "gd14", "difficulty": "hard", "type": "mcq",
         "question": "What is a design system?",
         "options": ["A single logo file", "A reusable set of components and standards", "A printing process", "A file format"],
         "answer": "A reusable set of components and standards"},
        {"id": "gd15", "difficulty": "hard", "type": "text",
         "question": "How would you improve accessibility for light gray text on a white background?"},
    ],

    "software engineering": [
        {"id": "se1", "difficulty": "easy", "type": "mcq",
         "question": "What does OOP stand for?",
         "options": ["Object Oriented Programming", "Open Operating Protocol", "Ordered Object Pattern", "Optimal Output Process"],
         "answer": "Object Oriented Programming"},
        {"id": "se2", "difficulty": "easy", "type": "mcq",
         "question": "Which symbol is used for comments in Python?",
         "options": ["//", "#", "<!--", "/*"],
         "answer": "#"},
        {"id": "se3", "difficulty": "easy", "type": "mcq",
         "question": "What is a variable?",
         "options": ["A fixed value", "A named storage location for data", "A type of loop", "A function"],
         "answer": "A named storage location for data"},
        {"id": "se4", "difficulty": "easy", "type": "mcq",
         "question": "Which of these is a version control system?",
         "options": ["Git", "Excel", "Photoshop", "MySQL Workbench"],
         "answer": "Git"},
        {"id": "se5", "difficulty": "easy", "type": "text",
         "question": "What is the difference between a function and a method?"},

        {"id": "se6", "difficulty": "medium", "type": "mcq",
         "question": "What is Big-O notation used for?",
         "options": ["Measuring code readability", "Measuring algorithm efficiency", "Naming variables", "Database design"],
         "answer": "Measuring algorithm efficiency"},
        {"id": "se7", "difficulty": "medium", "type": "text",
         "question": "Explain the difference between REST and SOAP APIs."},
        {"id": "se8", "difficulty": "medium", "type": "mcq",
         "question": "Which data structure uses FIFO order?",
         "options": ["Stack", "Queue", "Tree", "Graph"],
         "answer": "Queue"},
        {"id": "se9", "difficulty": "medium", "type": "text",
         "question": "What is version control and why is it important?"},
        {"id": "se10", "difficulty": "medium", "type": "mcq",
         "question": "What does SQL stand for?",
         "options": ["Structured Query Language", "Simple Query Logic", "Sequential Query List", "System Query Language"],
         "answer": "Structured Query Language"},

        {"id": "se11", "difficulty": "hard", "type": "text",
         "question": "Explain the SOLID principles briefly."},
        {"id": "se12", "difficulty": "hard", "type": "text",
         "question": "How would you design a scalable database schema for an e-commerce app?"},
        {"id": "se13", "difficulty": "hard", "type": "mcq",
         "question": "What is a race condition?",
         "options": ["A UI bug", "Two processes competing for shared resources unpredictably", "A slow network call", "A type of database index"],
         "answer": "Two processes competing for shared resources unpredictably"},
        {"id": "se14", "difficulty": "hard", "type": "text",
         "question": "Explain the tradeoffs between microservices and monolithic architecture."},
        {"id": "se15", "difficulty": "hard", "type": "text",
         "question": "How would you optimize a slow SQL query?"},
    ],

    "teaching": [
        {"id": "t1", "difficulty": "easy", "type": "mcq",
         "question": "What is a lesson plan?",
         "options": ["A test", "A structured outline for teaching a topic", "A grading rubric", "A classroom rule"],
         "answer": "A structured outline for teaching a topic"},
        {"id": "t2", "difficulty": "easy", "type": "mcq",
         "question": "Which of these is a formative assessment example?",
         "options": ["Final exam", "Quick in-class quiz", "Report card", "Graduation"],
         "answer": "Quick in-class quiz"},
        {"id": "t3", "difficulty": "easy", "type": "text",
         "question": "What is differentiated instruction?"},
        {"id": "t4", "difficulty": "easy", "type": "mcq",
         "question": "What does 'pedagogy' mean?",
         "options": ["A type of classroom", "The method and practice of teaching", "A grading system", "A school subject"],
         "answer": "The method and practice of teaching"},
        {"id": "t5", "difficulty": "easy", "type": "text",
         "question": "Why is classroom management important?"},

        {"id": "t6", "difficulty": "medium", "type": "text",
         "question": "How would you handle a disruptive student?"},
        {"id": "t7", "difficulty": "medium", "type": "mcq",
         "question": "What is Bloom's Taxonomy used for?",
         "options": ["Classifying learning objectives by complexity", "Grading exams", "Scheduling classes", "Measuring IQ"],
         "answer": "Classifying learning objectives by complexity"},
        {"id": "t8", "difficulty": "medium", "type": "text",
         "question": "What's the difference between formative and summative assessment?"},
        {"id": "t9", "difficulty": "medium", "type": "mcq",
         "question": "Which theory identifies visual, auditory, and kinesthetic learners?",
         "options": ["Bloom's Taxonomy", "Learning styles theory", "Piaget's theory", "Maslow's hierarchy"],
         "answer": "Learning styles theory"},
        {"id": "t10", "difficulty": "medium", "type": "text",
         "question": "How do you accommodate different learning paces in one classroom?"},

        {"id": "t11", "difficulty": "hard", "type": "text",
         "question": "Design a lesson plan outline for teaching a difficult concept to mixed-ability students."},
        {"id": "t12", "difficulty": "hard", "type": "text",
         "question": "How would you use technology to enhance student engagement?"},
        {"id": "t13", "difficulty": "hard", "type": "mcq",
         "question": "What is scaffolding in education?",
         "options": ["Removing all support immediately", "Providing temporary support that is gradually removed", "A type of test", "A classroom layout"],
         "answer": "Providing temporary support that is gradually removed"},
        {"id": "t14", "difficulty": "hard", "type": "text",
         "question": "How would you measure the long-term effectiveness of your teaching methods?"},
        {"id": "t15", "difficulty": "hard", "type": "text",
         "question": "Explain how you'd build an inclusive classroom environment for diverse learners."},
    ],
}